export const categoriesData = [
  {
    id: '1',
    name: 'School',
    iconName: 'graduation',
    percent: 75,
    amount: 375,
  },
  {
    id: '2',
    name: 'Bills',
    iconName: 'envelope-letter',
    percent: 50,
    amount: 250,
  },
  {
    id: '3',
    name: 'Eating Out',
    iconName: 'cup',
    amount: 175,
    percent: 25,
  },
  {
    id: '4',
    name: 'Entertainment',
    iconName: 'game-controller',
    percent: 23,
    amount: 145,
  },
  {
    id: '10',
    name: 'Transport',
    iconName: 'speedometer',
    percent: 22,
    amount: 150,
  },
  {
    id: '5',
    name: 'Shopping',
    iconName: 'basket-loaded',
    percent: 12,
    amount: 110,
  },
  {
    id: '6',
    name: 'General',
    iconName: 'wallet',
    percent: 10,
    amount: 100,
  },
  {
    id: '7',
    name: 'Holiday',
    iconName: 'plane',
    percent: 8,
    amount: 100,
  },
  {
    id: '8',
    name: 'Health',
    iconName: 'heart',
    percent: 5,
    amount: 80,
  },
  {
    id: '9',
    name: 'Clothes',
    iconName: 'handbag',
    percent: 5,
    amount: 50,
  },
];
