export const expensesData = [
  {
    id: '13',
    title: 'Buy a book',
    date: '2018-08-13',
    amount: -30,
    type: 'Credit card',
    category: 'General',
    categoryIcon: 'wallet',
  },
  {
    id: '12',
    title: 'Taxi to office',
    date: '2018-08-12',
    amount: -25,
    type: 'Credit card',
    category: 'Transport',
    categoryIcon: 'speedometer',
  },
  {
    id: '11',
    title: 'Launch with Alex',
    date: '2018-08-12',
    amount: -30.8,
    type: 'Credit card',
    category: 'Eating Out',
    categoryIcon: 'cup',
  },
  {
    id: '10',
    title: 'Pay check',
    date: '2018-08-12',
    amount: 3000,
    type: 'Bank transfert',
    category: 'Income',
    categoryIcon: 'credit-card',
  },
  {
    id: '9',
    title: 'Coffee with Jane',
    date: '2018-08-11',
    amount: -10,
    type: 'Cash',
    category: 'Eating Out',
    categoryIcon: 'cup',
  },
  {
    id: '8',
    title: 'Electricity bill',
    date: '2018-08-11',
    amount: -50,
    type: 'Credit Card',
    category: 'Bills',
    categoryIcon: 'envelope-letter',
  },
  {
    id: '7',
    title: 'Cinema with children',
    date: '2018-08-11',
    amount: -50,
    type: 'Credit Card',
    category: 'Entertainment',
    categoryIcon: 'game-controller',
  },
  {
    id: '6',
    title: 'Dinner with family',
    date: '2018-08-13',
    amount: -80,
    type: 'Cash',
    category: 'Eating Out',
    categoryIcon: 'cup',
  },
  {
    id: '5',
    title: 'shirt and jean for Adam',
    date: '2018-08-10',
    amount: -120,
    type: 'Credit Card',
    category: 'Car',
    categoryIcon: 'handbag',
  },
  {
    id: '4',
    title: 'Weekly shopping',
    date: '2018-08-10',
    amount: -150.5,
    type: 'Credit Card',
    category: 'Shopping',
    categoryIcon: 'basket-loaded',
  },
  {
    id: '3',
    title: 'Weekly shopping',
    date: '2018-08-10',
    amount: -150.5,
    type: 'Credit Card',
    category: 'Shopping',
    categoryIcon: 'basket-loaded',
  },
  {
    id: '2',
    title: 'Stuff from Amazon',
    date: '2018-08-10',
    amount: -25.5,
    type: 'Credit Card',
    category: 'Shopping',
    categoryIcon: 'basket-loaded',
  },
  {
    id: '1',
    title: 'Parking',
    date: '2018-08-10',
    amount: -5.5,
    type: 'Cash',
    category: 'Transport',
    categoryIcon: 'speedometer',
  },
];
